### ISSUE TITLE
Mask preview+ error

### ISSUE THREAD

**Issue by kakachiex2** [cubiq/ComfyUI_essentials#13]
This error message appear wen trying to extract a mask from a video with ImageBatch2imageList > BBox detector > Masks to masl list > Mask Preview+
![Screenshot 2024-02-02 023200](https://github.com/cubiq/ComfyUI_essentials/assets/1762112/2d0250aa-5b4c-4d44-8fe0-92cfbe642c46)

mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
mask len: 1080
2024-02-02 02:17:21,281 - root - ERROR - !!! Exception during processing !!!
2024-02-02 02:17:21,282 - root - ERROR - Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 397, in execute
    preview = mask.reshape((-1, 1, mask.shape[-2], mask.shape[-1])).movedim(1, -1).expand(-1, -1, -1, 3)
                                   ~~~~~~~~~~^^^^
IndexError: tuple index out of range

Prompt executed in 70.46 seconds
got prompt
2024-02-02 02:23:19,623 - root - ERROR - Failed to validate prompt for output 79:
2024-02-02 02:23:19,624 - root - ERROR - * (prompt):
2024-02-02 02:23:19,624 - root - ERROR -   - Required input is missing: images
2024-02-02 02:23:19,624 - root - ERROR - * VHS_VideoCombine 79:
2024-02-02 02:23:19,624 - root - ERROR -   - Required input is missing: images
2024-02-02 02:23:19,624 - root - ERROR - Output will be ignored
2024-02-02 02:23:19,629 - root - ERROR - Failed to validate prompt for output 71:
2024-02-02 02:23:19,630 - root - ERROR - * (prompt):
2024-02-02 02:23:19,630 - root - ERROR -   - Required input is missing: images
2024-02-02 02:23:19,630 - root - ERROR - * PreviewImage 71:
2024-02-02 02:23:19,630 - root - ERROR -   - Required input is missing: images
2024-02-02 02:23:19,630 - root - ERROR - Output will be ignored
2024-02-02 02:23:19,634 - root - ERROR - Failed to validate prompt for output 60:
2024-02-02 02:23:19,634 - root - ERROR - * (prompt):
2024-02-02 02:23:19,634 - root - ERROR -   - Required input is missing: images
2024-02-02 02:23:19,634 - root - ERROR - * VHS_VideoCombine 60:
2024-02-02 02:23:19,634 - root - ERROR -   - Required input is missing: images
2024-02-02 02:23:19,634 - root - ERROR - Output will be ignored
2024-02-02 02:24:37,807 - root - ERROR - !!! Exception during processing !!!
2024-02-02 02:24:37,808 - root - ERROR - Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 397, in execute
    preview = mask.reshape((-1, 1, mask.shape[-2], mask.shape[-1])).movedim(1, -1).expand(-1, -1, -1, 3)
                                   ~~~~~~~~~~^^^^
IndexError: tuple index out of range

Prompt executed in 78.46 seconds

**Comment by cubiq** [comment]
you should not convert to list before previewing

**Comment by kakachiex2** [comment]
Everything works except for the mask preview+ I try different method and get different error
![Screenshot 2024-02-02 030338](https://github.com/cubiq/ComfyUI_essentials/assets/1762112/29845460-ff2d-458a-ae62-5601d075b069)

**Comment by cubiq** [comment]
I feel it's a wrong format from the bbox, but I'll check. what tensor shape does the bbox mask has. You can use the tensor shape debug node to know

**Comment by kakachiex2** [comment]
were do I see the debug in the console

**Comment by kakachiex2** [comment]
Here is the workflow for you to test
![workflow](https://github.com/cubiq/ComfyUI_essentials/assets/1762112/76a807d1-9b74-453f-8e85-2b1dda130960)

**Comment by cubiq** [comment]
I'll check later, it's an easy fix

**Comment by kakachiex2** [comment]
Nice thanks I can't upload the video is bigger than 10mb
