### ISSUE TITLE
Error occurred when executing  PixelOEPixelize

### ISSUE THREAD

**Issue by Simwake** [cubiq/ComfyUI_essentials#25]
Error occurred when executing PixelOEPixelize+:

No module named 'pixeloe'

File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 1655, in execute
from pixeloe.pixelize import pixelize

**Comment by Simwake** [comment]
when install pixeloe occcurred

PS C:\Users\zyx> F:\ComfyUI_windows_portable\python_embeded\python.exe F:\ComfyUI_windows_portable\python_embeded\Scripts\pip.exe install pixeloe
Collecting pixeloe
  Using cached pixeloe-0.0.9.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\zyx\AppData\Local\Temp\pip-install-0daks4mr\pixeloe_12005fec8bb6470cbc498646925ee6e6\setup.py", line 2, in <module>
          from pixeloe import cli
      ModuleNotFoundError: No module named 'pixeloe'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
