### ISSUE TITLE
ModuleNotFoundError: No module named 'rembg'

### ISSUE THREAD

**Issue by VedanthB** [cubiq/ComfyUI_essentials#27]
!!! Exception during processing !!!
Traceback (most recent call last):
File "/src/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/src/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/src/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/src/ComfyUI/custom_nodes/ComfyUI_essentials/essentials.py", line 1604, in execute
from rembg import new_session as rembg_new_session
ModuleNotFoundError: No module named 'rembg'

**Comment by VedanthB** [comment]
Please Help

**Comment by VedanthB** [comment]
an update fixed it
