### ISSUE TITLE
Mask Preview error

### ISSUE THREAD

**Issue by robertvoy** [cubiq/ComfyUI_essentials#3]
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 318, in execute
    results = self.save_images(preview, filename_prefix, prompt, extra_pnginfo)
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1374, in save_images
    img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=self.compress_level)
AttributeError: 'MaskPreview' object has no attribute 'compress_level'
```

**Comment by liulsg** [comment]
same mistake
### ComfyUI Revision: 1754 [777f6b15] | Released on '2023-11-28'

Error occurred when executing MaskPreview+:

'MaskPreview' object has no attribute 'compress_level'

File "D:\AI\ComfyUI_c121\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_c121\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_c121\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_c121\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 318, in execute
results = self.save_images(preview, filename_prefix, prompt, extra_pnginfo)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_c121\ComfyUI\nodes.py", line 1374, in save_images
img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=self.compress_level)
