### ISSUE TITLE
error when i use sam model : !!! Exception during processing!!! '{}' is not of type 'array'

### ISSUE THREAD

**Issue by gsongX** [cubiq/ComfyUI_essentials#30]
![Snipaste_2024-04-30_05-00-32](https://github.com/cubiq/ComfyUI_essentials/assets/9738952/dec78e71-ef9d-469d-a41d-a43dcead56cb)
my workflow : 
![workflow](https://github.com/cubiq/ComfyUI_essentials/assets/9738952/9a783263-8f7b-424d-abe2-a6b5a3a4a046)

!!! Exception during processing!!! '{}' is not of type 'array'

Failed validating 'type' in schema:0.1:8188
    {'items': {'properties': {'data': {'items': {'type': 'number'},
                                       'type': 'array'},ustom_nodes\ComfyUI-Manager\extension-node-map.json
                              'label': {'type': 'integer'},\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
                              'type': {'type': 'string'}},
               'type': 'object'},ed recursive execution.
     'type': 'array'}atching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings
On instance:
    '{}' TripoSR model :  D:\AI-Starter\ComfyUI_windows\ComfyUI\models\checkpoints\3D\TripoSR.ckpt
Traceback (most recent call last):omfyUI_windows\ComfyUI\models\triposr\facebook/dino-vitb16
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True):RegisterTensorRTPluginsAsCustomO
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^re in the PATH or LD_LIBRARY_PATH
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))ExecutionProvider']
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^retrying.
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 1637, in execute
    img = rembg(img, session=rembg_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\python\Lib\site-packages\rembg\bg.py", line 260, in remove
    masks = session.predict(img, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\python\Lib\site-packages\rembg\sessions\sam.py", line 169, in predict
    validate(instance=prompt, schema=schema)
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\python\Lib\site-packages\jsonschema\validators.py", line 1312, in validate
    raise error
jsonschema.exceptions.ValidationError: '{}' is not of type 'array'

Failed validating 'type' in schema:
    {'items': {'properties': {'data': {'items': {'type': 'number'},
                                       'type': 'array'},
                              'label': {'type': 'integer'},
                              'type': {'type': 'string'}},
               'type': 'object'},
     'type': 'array'}

On instance:
    '{}'

**Comment by cubiq** [comment]
yeah I noticed, it's weird, I'll check but all the other models work

**Comment by rbbdz** [comment]
i have the same problem
