### ISSUE TITLE
Import failed / comfy ui / mac pinokio

### ISSUE THREAD

**Issue by TeeTTG** [cubiq/ComfyUI_essentials#42]
Trying to use "Product Photography Relight v3 " workflow, missing two nodes included in the essentials: ImageResize+ and MaskFromColor+. Tried to install Essentials few times through manager and through git url, restarted, updated comfy. Installed anaconda (someone on another thread wrote it could be useful).  import failed every time.

**Comment by JColdrick** [comment]
Running Windows  here, it's been fine updating until today, basically fails with this:

`Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\__init__.py", line 2, in <module>
    from .image import IMAGE_CLASS_MAPPINGS, IMAGE_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\image.py", line 736
    <<<<<<< HEAD
    ^^
SyntaxError: invalid syntax

Cannot import D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials module for custom nodes: invalid syntax (image.py, line 736)`

Just a guess but might be that LUT tweak from yesterday.  Thanks!

**Comment by EricRollei** [comment]
I get this console message when trying to update:
Update: ['https://github.com/cubiq/ComfyUI_essentials']
Cmd('git') failed due to: exit code(1)
  cmdline: git stash
  stdout: 'essentials.py: needs merge'
Update was successful.

**Comment by cubiq** [comment]
these are all different issues.

First of all try to delete the directory and reinstall. that should solve most of the problems.

@JColdrick that is weird, what version of python do you have?

**Comment by JColdrick** [comment]
Thanks, uninstalling and reinstalling fixed whatever was going on.

I'm running Python 3.11.8, FYI

**Comment by TeeTTG** [comment]
which directory? - I am totally noob with everything, so I may need quite thorough explanation. 🙏


Lähetetty iPhonesta

> Matteo Spinelli ***@***.***> kirjoitti 31.5.2024 kello 9.23:
> 
> First of all try to delete the directory and reinstall. that should solve most of the problems.
