### ISSUE TITLE
torchvision.transforms.v2

### ISSUE THREAD

**Issue by davedaverave** [cubiq/ComfyUI_essentials#53]
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_essentials/__init__.py", line 2, in <module>
    from .image import IMAGE_CLASS_MAPPINGS, IMAGE_NAME_MAPPINGS
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_essentials/image.py", line 7, in <module>
    import torchvision.transforms.v2 as T
ModuleNotFoundError: No module named 'torchvision.transforms.v2'

Cannot import /notebooks/ComfyUI/custom_nodes/ComfyUI_essentials module for custom nodes: No module named 'torchvision.transforms.v2'

**Comment by cubiq** [comment]
you have an old version of torch
