### ISSUE TITLE
import ComfyUI_essentials failed....

### ISSUE THREAD

**Issue by ykhasia** [cubiq/ComfyUI_essentials#57]
Log as below,  No module named 'node_helpers'... how to resolve  it ?
Traceback (most recent call last):
  File "E:\ProgramFiles\ai\ComfyUI-aki-v1.1\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ProgramFiles\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_essentials\__init__.py", line 2, in <module>
    from .image import IMAGE_CLASS_MAPPINGS, IMAGE_NAME_MAPPINGS
  File "E:\ProgramFiles\ai\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_essentials\image.py", line 5, in <module>
    from node_helpers import pillow
ModuleNotFoundError: No module named 'node_helpers'

**Comment by warcarlyp** [comment]
I have the same problem as you, it has been resolved.
The reason is missing files 'node_helpers.py',download from 'https://github.com/comfyanonymous/ComfyUI',add to your folder.

**Comment by cubiq** [comment]
you must have a relatively old version of comfyui installed
