### ISSUE TITLE
install fail, 

### ISSUE THREAD

**Issue by maxstewm** [cubiq/ComfyUI_essentials#78]
download suss,but install err.

i don't know why ?please help.

--------------------------------------------------------------
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\ComfyUI_essentials\__init__.py", line 2, in <module>
    from .image import IMAGE_CLASS_MAPPINGS, IMAGE_NAME_MAPPINGS
  File "F:\ComfyUI\custom_nodes\ComfyUI_essentials\image.py", line 8, in <module>
    import kornia
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\__init__.py", line 8, in <module>
    from . import (
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\augmentation\__init__.py", line 3, in <module>
    from kornia.augmentation._2d import (
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\augmentation\_2d\__init__.py", line 2, in <module>
    from kornia.augmentation._2d.intensity import *
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\augmentation\_2d\intensity\__init__.py", line 29, in <module>
    from kornia.augmentation._2d.intensity.plasma import RandomPlasmaBrightness, RandomPlasmaContrast, RandomPlasmaShadow
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\augmentation\_2d\intensity\plasma.py", line 5, in <module>
    from kornia.contrib import diamond_square
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\contrib\__init__.py", line 15, in <module>
    from .image_stitching import ImageStitcher
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\contrib\image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\feature\__init__.py", line 7, in <module>
    from .integrated import (
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\feature\integrated.py", line 17, in <module>
    from .lightglue import LightGlue
  File "F:\ComfyUI\.venv\Lib\site-packages\kornia\feature\lightglue.py", line 30, in <module>
    from flash_attn.modules.mha import FlashCrossAttention
  File "F:\ComfyUI\.venv\Lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "F:\ComfyUI\.venv\Lib\site-packages\flash_attn\flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: 找不到指定的程序。

Cannot import F:\ComfyUI\custom_nodes\ComfyUI_essentials module for custom nodes: DLL load failed while importing flash_attn_2_cuda: 找不到指定的程序。
-------------------------------------------------------------

**Comment by maxstewm** [comment]
i have already update comfyui, but the error is still not resolved。


pytorch version: 2.4.0+cu124
Python version: 3.11.9 
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 3GB : cudaMallocAsync
Using xformers cross attention
