### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by drewmolleur** [cubiq/ComfyUI_essentials#9]
Hello! This was working fine until recently. I've tried moving all nodes out of my custom nodes folder except Essentials and it still won't import after restarting.

Please help! Thanks in advance! :-)

![Screenshot 2023-12-28 at 3 23 43 PM](https://github.com/cubiq/ComfyUI_essentials/assets/7436233/689eb1a1-4330-4ff5-b0e7-9067c26be1e2)

**Comment by Syndulla** [comment]
Same issue here.

**Comment by cubiq** [comment]
You probably need to update comfyui

**Comment by drewmolleur** [comment]
That was the first thing I tried. 

![Screenshot 2023-12-29 at 9 30 31 AM](https://github.com/cubiq/ComfyUI_essentials/assets/7436233/3f2d3c1a-75f4-4e68-af8e-286ecb655499)
![Screenshot 2023-12-29 at 9 30 39 AM](https://github.com/cubiq/ComfyUI_essentials/assets/7436233/f4ce231d-813d-400e-90e9-fae5434aa01e)
![Screenshot 2023-12-29 at 9 30 44 AM](https://github.com/cubiq/ComfyUI_essentials/assets/7436233/2e33c774-726a-4f9c-923b-f9ed3a248511)

**Comment by fine4546** [comment]
Traceback (most recent call last):
  File "/raid/ComfyUI/nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/raid/ComfyUI/custom_nodes/ComfyUI_essentials/__init__.py", line 1, in <module>
    from .essentials import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/raid/ComfyUI/custom_nodes/ComfyUI_essentials/essentials.py", line 12, in <module>
    import torchvision.transforms.v2 as T
ModuleNotFoundError: No module named 'torchvision.transforms.v2'


didnot Found torchvision.transforms.v2    please version checkingggggg

**Comment by drewmolleur** [comment]
@fine4546 - this is perhaps a separate issues. What machine are you running this on? I'm on a m1 Mac.

**Comment by fine4546** [comment]
same import error, i could not import,  
Detailed error content

**Comment by cubiq** [comment]
update comfy dependencies

**Comment by tutnyal** [comment]
After updating all comfy failed. I updated my Anaconda environment and it worked! `conda update --all`
